---
version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: tacotaco
    container_name: tacotaco
    hostname: tacotaco
    command: /usr/src/app/node_modules/.bin/node server.js
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file: ./server/.env
    environment:
      - ENVIRONMENT=development

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
