---
version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: tacotaco
    container_name: tacotaco
    hostname: tacotaco
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5050:5050"
    env_file: ./server/.env
    environment:
      - ENVIRONMENT=staging
    restart: unless-stopped
    command: "yarn knex && yarn start"

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
